-- test_ed25519.lua — SHA-512 and Ed25519 signing against known answers.
-- RFC 8032 section 7.1 TESTs 1 and 2, plus vectors generated by Node's native
-- (OpenSSL) Ed25519. Run this under a PUC Lua 5.1 too, not only LuaJIT: DCS's
-- Mission Editor is PUC 5.1 with no bit library, which is the whole reason
-- these modules are pure arithmetic.
package.path = '../lua/dcs_sms_me/?.lua;../lua/?.lua;' .. package.path

local sha512 = require('dcs_sms_me.sha512')
local ed     = require('dcs_sms_me.ed25519')

local failures = 0
local function check(n, ok, msg) if ok then print('PASS '..n) else print('FAIL '..n..': '..tostring(msg)); failures=failures+1 end end
local function unhex(h) return (h:gsub('..', function(c) return string.char(tonumber(c, 16)) end)) end
local function hex(s) return (s:gsub('.', function(c) return string.format('%02x', c:byte()) end)) end

-- ---- SHA-512 (includes the 111/112-byte padding boundary) ----
local SHA = {
    { '', 'cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e' },
    { 'abc', 'ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f' },
    { string.rep('a', 111), 'fa9121c7b32b9e01733d034cfc78cbf67f926c7ed83e82200ef86818196921760b4beff48404df811b953828274461673c68d04e297b0eb7b2b4d60fc6b566a2' },
    { string.rep('a', 112), 'c01d080efd492776a1c43bd23dd99d0a2e626d481e16782e75d54c2503b5dc32bd05f0f1ba33e568b88fd2d970929b719ecbb152f58f130a407c8830604b70ca' },
}
for i, v in ipairs(SHA) do
    check('sha512 vector ' .. i .. ' (' .. #v[1] .. ' bytes)', sha512.hex(v[1]) == v[2], sha512.hex(v[1]))
end
check('sha512 digest is 64 raw bytes', #sha512.digest('x') == 64)

-- ---- Ed25519 ----
local V = {
    { seed = '9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60',
      pub  = 'd75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a',
      msg  = '',
      sig  = 'e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b' },
    { seed = '4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb',
      pub  = '3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c',
      msg  = '72',
      sig  = '92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00' },
    { seed = '60a88e3cf36210c0e1e18fe9e9c830d8cbe283389a12616de9ef34249126d3ea',
      pub  = 'f88f3d82ff432fddaab1067927596eb0ffd6b0046669cf44f5fcec9009c3a2c4',
      msg  = '1b24778c1512ac38541d133be6afc5715b52f72e528eb3d1a2af61de6d7032',
      sig  = 'bf02ccf6d16e11e7a35baa1294f269304ec06a5b19c508ad2d5a57d31caf2dcfa35ae0fc7c2c18c5eb4d7cf11c59e06257126c3ae0a3b2a3f28051195748ca09' },
    { seed = '741dfce35ca5be4b9117214f5b5e7df0b0b4e6950d6d24a8d16fe78fc706ca00',
      pub  = 'c89eed8301ce5b10b11fd4e08e655ab0b547b11f97f2b6d79abe57b3c0074c1b',
      msg  = '115488770b418fa897b9e7c538c87d78c2999d9ce77d8e9f5c664b386e52553fe042eb71a73611ae90f0e172b10f896347407a0cbdeddb91ef48702307b4670b91c17847a13a5bd0485026d8d3c7f6b1b053e76054fa94786d2a5a9cb8ac11d56bdd9e8c1280735e2ad13c15a0e6c185',
      sig  = 'f0bf8912424070dce98e9cd0a7929cbbc895146bb9475def1796a957152bfd2a4ff25a1e3df511f6a667168b216395651d3f2970b00d66836fdf9305fe725301' },
    { seed = '228639ef71b6d22ee0de20942c323c62801e980c0184f5e19dbef6a53b7d86b9',
      pub  = 'bf74282846b7929d4bcde8d2e85bbe0b1211d31b42739d0b3ec4c1df107ee49e',
      msg  = '6463732d736d732d7375626d69742f310a7878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878',
      sig  = 'b435d6b7b3043ed9d7671a0b52b63b1c58658671279a36c1ec89cc15632b072da23aa903592aab7c89748ca46ed06eb085bfabd2fba44383c043e12b44790107' },
}
for i, v in ipairs(V) do
    local pub = ed.public_key(unhex(v.seed))
    check('ed25519 vector ' .. i .. ' public key', hex(pub) == v.pub, hex(pub))
    local sig = ed.sign(unhex(v.seed), pub, unhex(v.msg))
    check('ed25519 vector ' .. i .. ' signature (' .. (#v.msg / 2) .. '-byte msg)', hex(sig) == v.sig, hex(sig))
end

-- tick is called while working, and inside a coroutine the work can be
-- spread across resumes (how the Share dialog keeps the editor responsive).
local ticks = 0
local co = coroutine.create(function()
    return ed.sign(unhex(V[1].seed), unhex(V[1].pub), '', function() ticks = ticks + 1; coroutine.yield() end)
end)
local resumes, done, sig = 0, false, nil
while not done do
    local ok, res = coroutine.resume(co)
    resumes = resumes + 1
    if not ok then error(res) end
    if coroutine.status(co) == 'dead' then done = true; sig = res end
end
check('sign yields via tick (spread over many resumes)', ticks >= 16 and resumes == ticks + 1, ticks .. '/' .. resumes)
check('yielding sign gives the same signature', hex(sig) == V[1].sig)

check('bad seed length rejected', not pcall(ed.public_key, 'short'))

if failures > 0 then os.exit(1) end
print('All ed25519 tests passed.')
